### ISSUE TITLE
duplicate .exe's

### ISSUE THREAD

**Issue by bvanevery** [cr88192/bgbtech_engine#3]
The top level bgbtech_engine contains many .exe's, which also exist in subdirectories such as \apps.  .exe's in subdirectories have .pdb files associated with them, but .exe's at the top level do not.  This has many liabilities: 1) people trying out the code can test and end up filing bug reports against different .exe's or .exe execution environments, 2) .pdb's are not consistently available and may refer to wrong stuff, and 3) the download is unnecessarily bigger.

This is probably an artifact of an inappropriate build system, that was not designed for deployment to a git repository.  Build artifacts should not be part of a source tree.  Even .exe's and .lib's are generally part of a binary release, not a source code release.

**Comment by cr88192** [comment]
mostly it is a recursive build, where each make stage copies the EXEs and DLLs from the sub-stage.
in general, it works pretty good, and Visual Studio automagically finds the PDB's.

though, it seems to not work as reliably if things are copied to a different PC.
could possibly change the copies to moves though, and clean the PDB's from GH (since chances are they don't work unless built locally anyways).

**Comment by bvanevery** [comment]
When I open a command line, go to my \bgbtech_engine directory, and run engine0.exe, it crashes.  If I opt to debug it with Visual Studio, it doesn't find a darned thing .pdb file wise.  Just says the stack isn't available for scrutiny.

If I open a command line, go to the \bgbtech_engine\apps directory, and try to run that copy of engine0.exe, it won't because all the .dll's are missing.  Doesn't matter if .pdb files are there, they can't do any good.

Most people at a minimum would settle on a \bin directory convention for .exe's and .dll's.  On Linux, people argue about where shared libraries are supposed to go.  Or maybe there's no argument, the answer may be "not in \bin".  I just got into an argument with an Urho3D developer about it recently.  Their build was CMake based, so they had a lot of options for deciding output directory issues.

**Comment by cr88192** [comment]
ok. it all "just works" on my end, but may be limited to things built locally.

part of the reason things execute from the top-level directory is this is how it finds the 'resource' directory and the config file to mount other things in the VFS. executing from a sub-directory would make it less obvious how to go about setting up the VFS (ex: top-level-finding or looking for a config file or something).

for Linux, there is a bit of a nasty mess. don't really like how Linux resolves SOs and would much rather if it worked more like on Windows.

**Comment by bvanevery** [comment]
I would suggest that the most important thing at present, is not Linux, but picking One True Place [TM] for .exe's on Windows to live.

**Comment by cr88192** [comment]
that would probably be in the top-level directory. this is also true of most of the DLLs, except a few which go in resource. tried cleaning DLLs, but couldn't find a good way to exclude resource from the 'clean' process.

noted a crash if it fails to load client DLL, fixing the crash results in a black screen with only the console (the menu and similar is currently done by the client DLL).
have been meaning to get back to the "new spiffy menu" thing, keep getting sidetracked.

**Comment by bvanevery** [comment]
A good way to keep from getting sidetracked, is to work on issues that people file in a bug tracker, until they are done.  :-)  Assuming they're tractable.

**Comment by cr88192** [comment]
that was part of what making my engine work on RASWGL was about:
run renderer in a controlled environment, so I could look for things operating out-of-spec for OpenGL 1.2. however... what things I found/fixed may not have fixed the issue.

but, OTOH, I now have slightly prettier Quake3 on RASWGL as a result (but it is no longer purely scalar code, as I ended up using a few SSE2 intrinsics in the rasterizer).

**Comment by bvanevery** [comment]
That's not this issue / bug.  This one is "duplicate .exe's".  Part of the point of a bug tracker, is to deal with only one isolated thing at a time.  Filing an issue isn't a request that you work on fixing everything, only this 1 specific thing.

If you are responding to these messages via email, and not noticing the subject line, I would urge you to be more careful so that others (if any people come) will be less confused about what is being referred to.  Myself, I don't answer anything by email.  I click on the GitHub link at the bottom of the email and then answer there.  Makes it easier to see the context of the bug.

**Comment by cr88192** [comment]
in any case...

this has mostly already been addressed in the 'clean.sh' script:
- rm -rf `find */ -name \*.exe`

now only the top-level EXEs are present once cleaned.
DLLs are a harder issue though.

OTOH, now it takes a lot longer to recompile from the repo, but luckily I primarily develop from another location (and manually sync stuff by copying files around).

IOW: always run the engine EXE's from the top-level directory.

**Comment by bvanevery** [comment]
I just pulled and don't see any duplicate .exe's in the subdirectories, so I'm calling this closed.
